name: Actgions workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Js Actgion
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Jovis
      - name: Log Greeting time
        run: echo ${{steps.greet.output.time}}