## Follow the repository's Code Tour for configuration. Threshold: 8%

name: cicd

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
  pull_request_target:
    branches:
      - master
    types:
      - synchronize
      - opened
      - reopened
      - unlocked
  workflow_dispatch:

env:
  DOCKER_FILE: "Dockerfile"
  GH_REGISTRY_NAME: ghcr.io


jobs:
  build:
    if: |
      (github.event_name == 'pull_request_target' && github.actor == 'dependabot[bot]') ||
      (github.event_name == 'push' && github.actor != 'dependabot[bot]')
    timeout-minutes: 20
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: "development"
            environment_url: "https://ftegaas-api.lemans-sandbox.rockwellautomation.com/api/v1/Gateways/connection"
          - environment: "prerelease"
            environment_url: "https://ftegaas-api.cloud-dev.rockwellautomation.com/api/v1/Gateways/connection"
    outputs:
      build_version: ${{ env.BUILD_VERSION }}
      docker_tag: ${{ env.DOCKER_TAG }}
    concurrency:
      group: container-build-${{ github.ref || 'pull-request' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ (github.event_name == 'pull_request_target' && github.event.pull_request.head.sha) || github.ref_name }}

      - name: Checkout RA Action Repo
        uses: actions/checkout@v3
        with:
          repository: Rockwell-Automation-Inc/actions
          ref: master
          token: ${{ secrets.READ_GITHUB_ACTIONS_PAT }}
          path: .github/actions

      - name: Determine next tag
        id: next_tag
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: master
          PRERELEASE: true
          PRERELEASE_SUFFIX: ${{ matrix.environment }}
          DRY_RUN: true

      - name: Create environment variable BUILD_VERSION
        run: |
          echo "BUILD_VERSION=${{ steps.next_tag.outputs.new_tag }}" >> $GITHUB_ENV

      # ... Build steps here ...
      - name: Build Docker image
        run: |
          docker build . --file ${{ env.DOCKER_FILE }} --tag buildimage --build-arg appurl=${{ matrix.environment_url }} --build-arg build_version=${BUILD_VERSION}

      # - name: Docker Login to GitHub Container Registry
      #   if: github.ref == 'refs/heads/master'       
      #   run: |
      #     echo ${{ secrets.READ_WRITE_GITHUB_PACKAGES_PAT }} | docker login ${{ env.GH_REGISTRY_NAME }} --username ${{ secrets.READ_WRITE_GITHUB_PACKAGES_USER }} --password-stdin

  #     - uses: ./.github/actions/common-outputs
  #       if: github.ref == 'refs/heads/master'
  #       id: common

  #     - name: Push the Docker image
  #       if: github.ref == 'refs/heads/master'
  #       run: |
  #         docker tag buildimage ${DOCKER_TAG}:${BUILD_VERSION}
  #         docker push ${DOCKER_TAG}:${BUILD_VERSION}
  #       env:
  #         DOCKER_TAG: ${{ steps.common.outputs.container-registry-docker-tag }} >> $GITHUB_ENV

  #     - name: post-build-scanning-test
  #       if: github.ref == 'refs/heads/master'
  #       uses: Rockwell-Automation-Inc/workflows/.github/workflows/workflow_call_images_post_build_scanning_test.yaml@master
  #       with:
  #         environment: ${{ matrix.environment }}
  #         version: ${{ needs.build.outputs.build_version }}
  #         image: "Image"
  #         integrity_check: false
  #       secrets: inherit

  # publish-image-to-nonprod-acr:
  #   if: github.ref == 'refs/heads/master'
  #   needs: [build, post-build-scanning-test]
  #   runs-on: self-hosted
  #   steps:

  #     - name: Pull Docker image from GitHub Container Registry
  #       run: |
  #         echo ${{ secrets.READ_WRITE_GITHUB_PACKAGES_PAT }} | docker login ${{ env.GH_REGISTRY_NAME }} --username ${{ secrets.READ_WRITE_GITHUB_PACKAGES_USER }} --password-stdin
  #         docker pull ${{ needs.build.outputs.docker_tag }}:${{ needs.build.outputs.build_version }}


  #     - name: Login to Nonprod ACR  
  #       uses: docker/login-action@v2
  #       with:
  #         registry: ${{ secrets.EGAASACRC_NONPROD_LOGIN_SERVER }}
  #         password: ${{ secrets.EGAASACRC_NONPROD_LOGIN_PASSWORD }}
  #         username: ${{ secrets.EGAASACRC_NONPROD_LOGIN_USERNAME }}

  #     - name: Tag and Push Docker image to Nonprod ACR       
  #       run: |
  #         docker tag ${{ needs.build.outputs.docker_tag }}:${{ needs.build.outputs.build_version }} ${{ secrets.EGAASACRC_NONPROD_LOGIN_SERVER }}/$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]'):${{ needs.build.outputs.build_version }}
  #         docker push ${{ secrets.EGAASACRC_NONPROD_LOGIN_SERVER }}/$(echo "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]'):${{ needs.build.outputs.build_version }}

  # create-sandbox-release:
  #   needs: [publish-sandbox-image-to-nonprod-acr]
  #   uses: Rockwell-Automation-Inc/workflows/.github/workflows/workflow_call_create_release.yaml@master
  #   with:
  #     release_suffix: development
  #   secrets:
  #     token: ${{ secrets.READ_GITHUB_ACTIONS_PAT }}

  
