name: Matrix workflow

on: [push]


jobs:
  includes_only:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - site: "production"
            datacenter: "site-a"
          - site: "staging"
            datacenter: "site-b"
    steps:
      - name: echo Site
        run: echo ${{ matrix.site }}
      - name: echo Site
        run: echo ${{ matrix.datacenter }}