name: Matrix workflow

on: [push]


env:
  DATACENTER1: "site-a"

jobs:
  includes_only:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - site: "production"
            datacenter: "site-a"
          - site: "staging"
            datacenter: ${{ env.datacenter2 }}
    steps:
      - name: echo Site
        run: echo ${{ matrix.site }}
      - name: echo Site
        run: echo ${{ matrix.datacenter }}